### ISSUE TITLE
动画的过渡我觉得应该换一下

### ISSUE THREAD

**Issue by epver** [hzzly/xyy-vue#2]
由于动画都是右往左推，导致所有页面都是右往左推，效果不是很好，可以考虑用渐变就行了

**Comment by Wilson-hu** [comment]
![2017-04-24_170317](https://cloud.githubusercontent.com/assets/18467823/25329893/332e8c7c-2910-11e7-8b8e-fcf61459eef6.png)
大神，为什么在本地运行的时候会报这种错误

**Comment by epver** [comment]
反向代理配置看下， 在config 文件夹中的index.js里面的配置
